Repository sunnyshahabuddin/Coding-Ninjas, pull requests merged in 2021-10, with the labels that each got.

#40 Count Inversions
  Countinversions
Labels: enhancement, hacktoberfest-accepted

#41 Linked List Basic Inserting New Node
  LinkedList/LinkedListBasicInsertingNewNode.java
  LinkedList/Linkedlist basic
Labels: hacktoberfest-accepted

#42 Dadjokes
  dadjokes.html
Labels: hacktoberfest-accepted

#44 wikiapi.js
  wikiapi.js
Labels: hacktoberfest-accepted

#43 Bidirectionalsearch.cpp
  Bidirectionalsearch.cpp
Labels: hacktoberfest-accepted

#45 Magics Squares
  Magic_Square.java
Labels: hacktoberfest-accepted

#46 Create longestcommonsubsequnce.cpp
  longestcommonsubsequnce.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#47 Sprintf in C
  sprintfinC.c
Labels: hacktoberfest-accepted

#49 Create knapsack.cpp
  knapsack.cpp
Labels: hacktoberfest-accepted

#48 Print BST key
  PrintBSTkeysinrange.java
Labels: hacktoberfest-accepted

#50 Create coinchange.cpp
  coinchange.cpp
Labels: enhancement, hacktoberfest-accepted

#52 Count ways to assign unique cap to every person
  Bitmaskingdp.cpp
Labels: enhancement, hacktoberfest-accepted

#51 Create bitmasking.cpp
  bitmasking.cpp
Labels: enhancement, hacktoberfest-accepted

#53 Create maxlengthchain.cpp
  maxlengthchain.cpp
Labels: enhancement, hacktoberfest-accepted

#54 lobtt.cpp
  lobtt.cpp
Labels: hacktoberfest-accepted

#55 Create targetsumtriplet.cpp
  targetsumtriplet.cpp
Labels: hacktoberfest-accepted

#58 Create mergesort.cpp
  mergesort.cpp
Labels: hacktoberfest-accepted

#57 Create quicksort.cpp
  quicksort.cpp
Labels: hacktoberfest-accepted

#56 Create power.cpp
  power.cpp
Labels: hacktoberfest-accepted

#62 Create insertionsort.cpp
  insertionsort.cpp
Labels: hacktoberfest-accepted

#61 Create selectionsort.cpp
  selectionsort.cpp
Labels: hacktoberfest-accepted

#60 Create binarysearch.cpp
  binarysearch.cpp
Labels: hacktoberfest-accepted

#59 Create linearsearch.cpp
  linearsearch.cpp
Labels: hacktoberfest-accepted

#76 Create caesar_sender.py
  caesar_sender.py
Labels: hacktoberfest-accepted

#75 Create ceaser_reviver.py
  ceaser_reviver.py
Labels: hacktoberfest-accepted

#74 Create multichat_server.py
  multichat_server.py
Labels: hacktoberfest-accepted

#73 Create multichat_client.py
  multichat_client.py
Labels: hacktoberfest-accepted

#72 Create osprime.py
  osprime.py
Labels: hacktoberfest-accepted

#16 Create Largest Windmill.cpp
  Largest Windmill.cpp
Labels: hacktoberfest-accepted

#71 Create TernarySearch.cpp
  TernarySearch.cpp
Labels: hacktoberfest-accepted

#70 Create Aho-corasick.cpp
  Aho-corasick.cpp
Labels: hacktoberfest-accepted

#69 Create Z-function.cpp
  Z-function.cpp
Labels: hacktoberfest-accepted

#68 Create RabinKarp Algorithm
  RabinKarp
Labels: hacktoberfest-accepted

#67 Create fact.cpp
  fact.cpp
Labels: hacktoberfest-accepted

#92 Create kthroot.cpp
  kthroot.cpp
Labels: hacktoberfest-accepted

#91 Create stringsort.cpp
  stringsort.cpp
Labels: hacktoberfest-accepted

#90 Create matrixsearch.cpp
  matrixsearch.cpp
Labels: hacktoberfest-accepted

#89 Create count_setbits.cpp
  count_setbits.cpp
Labels: hacktoberfest-accepted

#88 Create hulk.cpp
  hulk.cpp
Labels: hacktoberfest-accepted

#87 Create unique.cpp
  unique.cpp
Labels: hacktoberfest-accepted

#86 Create nextpermutation.cpp
  nextpermutation.cpp
Labels: hacktoberfest-accepted

#85 Create activity.cpp
  activity.cpp
Labels: hacktoberfest-accepted

#84 Create rainwater.cpp
  rainwater.cpp
Labels: hacktoberfest-accepted

#83 Create bitonic.cpp
  bitonic.cpp
Labels: hacktoberfest-accepted

#82 Create maxsum.cpp
  maxsum.cpp
Labels: hacktoberfest-accepted

#81 Create anish_1.cpp
  anish_1.cpp
Labels: hacktoberfest-accepted

#80 Create k100_4.cpp
  k100_4.cpp
Labels: hacktoberfest-accepted

#79 Create k100_3.cpp
  k100_3.cpp
Labels: hacktoberfest-accepted

#78 Create k100_2.cpp
  k100_2.cpp
Labels: hacktoberfest-accepted

#77 Create keshavvats1.cpp
  keshavvats1.cpp
Labels: hacktoberfest-accepted

#93 Create upperbound.cpp
  upperbound.cpp
Labels: hacktoberfest-accepted

#95 Create aggresivecow.cpp
  aggresivecow.cpp
Labels: hacktoberfest-accepted

#96 Create painterpartition.cpp
  painterpartition.cpp
Labels: hacktoberfest-accepted

#94 Create bookaloocation.cpp
  bookaloocation.cpp
Labels: hacktoberfest-accepted
