Repository sunnyshahabuddin/Coding-Ninjas, pull requests merged in 2023-10, with the labels that each got.

#130 Create linked_list_simplified.c++
  LinkedList/linked_list_simplified.c++
Labels: good first issue, hacktoberfest-accepted

#134 Create stack_queue_simplified.c++
  StackAndQueue/stack_queue_simplified.c++
Labels: hacktoberfest-accepted

#133 Create time_taken_code.c++
  Time Complexity/time_taken_code.c++
Labels: hacktoberfest-accepted

#132 Create hash_map_simplified.c++
  HashMaps/hash_map_simplified.c++
Labels: enhancement, hacktoberfest-accepted

#131 Create bst_simplified.c++
  BST/bst_simplified.c++
Labels: enhancement, hacktoberfest-accepted

#142 Create todo.cpp
  todo.cpp
Labels: enhancement, hacktoberfest-accepted

#141 Create multithreading.cpp
  multithreading.cpp
Labels: enhancement, hacktoberfest-accepted

#140 Create lowest_common_ancestor.cpp
  lowest_common_ancestor.cpp
Labels: enhancement, hacktoberfest-accepted

#139 Create longest_common_subsequence.cpp
  longest_common_subsequence.cpp
Labels: enhancement, hacktoberfest-accepted

#138 Create shortest_distance_bw_cities.cpp
  shortest_distance_bw_cities.cpp
Labels: enhancement, hacktoberfest-accepted

#137 Check anagram
  substring_check.cpp
Labels: enhancement, hacktoberfest-accepted

#136 Create file_manipulation_with_C_plus_plus.cpp
  file_manipulation_with_C_plus_plus.cpp
Labels: enhancement, hacktoberfest-accepted

#135 Create phonebook.cpp
  phonebook.cpp
Labels: enhancement, hacktoberfest-accepted
